# Generated by Django 5.1 on 2024-09-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grower',
            name='geolat',
        ),
        migrations.RemoveField(
            model_name='grower',
            name='geolong',
        ),
        migrations.AddField(
            model_name='grower',
            name='barangay',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grower',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grower',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grower',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
