# Generated by Django 5.1 on 2024-12-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_remove_grower_geolat_remove_grower_geolong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grower',
            name='Email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
