# Generated by Django 5.1 on 2024-09-21 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_user', '0002_remove_grower_geolat_remove_grower_geolong_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ls_code', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age_in_days', models.IntegerField()),
                ('generation', models.IntegerField()),
                ('batch_no', models.IntegerField()),
                ('tag_color', models.CharField(max_length=50)),
                ('date_recorded', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9)),
                ('description', models.TextField(blank=True, null=True)),
                ('grower', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='farm_locations', to='auth_user.grower')),
            ],
        ),
        migrations.CreateModel(
            name='Dispersal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispersal_date', models.DateField()),
                ('grower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.grower')),
                ('farmlocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.farmlocation')),
                ('chickens_dispersed', models.ManyToManyField(to='livestock.livestock')),
            ],
        ),
        migrations.CreateModel(
            name='LivestockFamily',
            fields=[
                ('family_id', models.CharField(max_length=155, primary_key=True, serialize=False)),
                ('cage_location', models.CharField(max_length=100)),
                ('date_recorded', models.DateField()),
                ('brood_generation_number', models.IntegerField(blank=True, default=1, null=True)),
                ('hens', models.ManyToManyField(blank=True, related_name='family_female', to='livestock.livestock')),
                ('roosters', models.ManyToManyField(blank=True, related_name='family_male', to='livestock.livestock')),
            ],
        ),
        migrations.AddField(
            model_name='livestock',
            name='livestock_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livestock.livestockfamily'),
        ),
    ]
