# Generated by Django 5.1.6 on 2025-03-25 03:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_user', '0003_alter_grower_linked_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockFamily',
            fields=[
                ('family_id', models.CharField(max_length=155, primary_key=True, serialize=False, unique=True)),
                ('cage_location', models.CharField(max_length=100)),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
                ('brood_generation_number', models.IntegerField(blank=True, default=1, null=True)),
                ('max_roosters', models.IntegerField(default=1)),
                ('max_hens', models.IntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='FarmLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('grower', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='farm_locations', to='auth_user.grower')),
            ],
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ls_code', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age_in_days', models.IntegerField()),
                ('generation', models.IntegerField()),
                ('batch_no', models.IntegerField()),
                ('tag_color', models.CharField(max_length=50)),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='livestock_images/')),
                ('livestock_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livestock.livestockfamily')),
            ],
        ),
        migrations.CreateModel(
            name='Dispersal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispersal_date', models.DateField()),
                ('grower', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='auth_user.grower')),
                ('farmlocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.farmlocation')),
                ('families_dispersed', models.ManyToManyField(to='livestock.livestockfamily')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=225)),
                ('message_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
