# Generated by Django 5.1.6 on 2025-03-25 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispersal',
            name='grower',
        ),
    ]
