# Generated by Django 5.1 on 2024-09-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestockfamily',
            name='hens',
        ),
        migrations.RemoveField(
            model_name='livestockfamily',
            name='roosters',
        ),
    ]
