# Generated by Django 5.1 on 2024-09-23 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_remove_livestockfamily_hens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='date_recorded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
