# Generated by Django 5.1.6 on 2025-03-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_remove_dispersal_grower'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_roosters', models.IntegerField(default=1, help_text='Max roosters per family')),
                ('max_hens', models.IntegerField(default=8, help_text='Max hens per family')),
            ],
        ),
    ]
