# Generated by Django 5.1 on 2024-09-23 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_alter_livestock_date_recorded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockfamily',
            name='date_recorded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
