# Generated by Django 5.1 on 2024-09-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0005_alter_farmlocation_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispersal',
            name='chickens_dispersed',
        ),
        migrations.AddField(
            model_name='dispersal',
            name='families_dispersed',
            field=models.ManyToManyField(to='livestock.livestockfamily'),
        ),
    ]
