# Generated by Django 5.1 on 2024-12-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0007_message_delete_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
